package example.Bean;
// Generated 2017-4-9 20:37:54 by Hibernate Tools 4.3.1



/**
 * Adminster generated by hbm2java
 */
public class Adminster  implements java.io.Serializable {


     private int adId;
     private String adname;
     private String adpw;

    public Adminster() {
    }

    public Adminster(int adId, String adname, String adpw) {
       this.adId = adId;
       this.adname = adname;
       this.adpw = adpw;
    }
   
    public int getAdId() {
        return this.adId;
    }
    
    public void setAdId(int adId) {
        this.adId = adId;
    }
    public String getAdname() {
        return this.adname;
    }
    
    public void setAdname(String adname) {
        this.adname = adname;
    }
    public String getAdpw() {
        return this.adpw;
    }
    
    public void setAdpw(String adpw) {
        this.adpw = adpw;
    }




}


