package example.Bean;
// Generated 2017-4-9 20:37:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private int cartId;
     private int userId;
     private int number;
     private int goodId;
     private String image;
     private BigDecimal money;
     private Integer orderId;

    public Cart() {
    }

	
    public Cart(int cartId, int userId, int number, int goodId) {
        this.cartId = cartId;
        this.userId = userId;
        this.number = number;
        this.goodId = goodId;
    }
    public Cart(int cartId, int userId, int number, int goodId, String image, BigDecimal money, Integer orderId) {
       this.cartId = cartId;
       this.userId = userId;
       this.number = number;
       this.goodId = goodId;
       this.image = image;
       this.money = money;
       this.orderId = orderId;
    }
   
    public int getCartId() {
        return this.cartId;
    }
    
    public void setCartId(int cartId) {
        this.cartId = cartId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public int getGoodId() {
        return this.goodId;
    }
    
    public void setGoodId(int goodId) {
        this.goodId = goodId;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public BigDecimal getMoney() {
        return this.money;
    }
    
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }




}


