package example.Bean;
// Generated 2017-4-9 20:37:54 by Hibernate Tools 4.3.1



/**
 * Chef generated by hbm2java
 */
public class Chef  implements java.io.Serializable {


     private int chefId;
     private String chefname;
     private int shopId;
     private String cplace;

    public Chef() {
    }

	
    public Chef(int chefId, int shopId) {
        this.chefId = chefId;
        this.shopId = shopId;
    }
    public Chef(int chefId, String chefname, int shopId, String cplace) {
       this.chefId = chefId;
       this.chefname = chefname;
       this.shopId = shopId;
       this.cplace = cplace;
    }
   
    public int getChefId() {
        return this.chefId;
    }
    
    public void setChefId(int chefId) {
        this.chefId = chefId;
    }
    public String getChefname() {
        return this.chefname;
    }
    
    public void setChefname(String chefname) {
        this.chefname = chefname;
    }
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }
    public String getCplace() {
        return this.cplace;
    }
    
    public void setCplace(String cplace) {
        this.cplace = cplace;
    }




}


