package example.Bean;
// Generated 2017-4-9 20:37:54 by Hibernate Tools 4.3.1



/**
 * Eimage generated by hbm2java
 */
public class Eimage  implements java.io.Serializable {


     private int eid;
     private String eplace;
     private int shopId;

    public Eimage() {
    }

	
    public Eimage(int eid, int shopId) {
        this.eid = eid;
        this.shopId = shopId;
    }
    public Eimage(int eid, String eplace, int shopId) {
       this.eid = eid;
       this.eplace = eplace;
       this.shopId = shopId;
    }
   
    public int getEid() {
        return this.eid;
    }
    
    public void setEid(int eid) {
        this.eid = eid;
    }
    public String getEplace() {
        return this.eplace;
    }
    
    public void setEplace(String eplace) {
        this.eplace = eplace;
    }
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }




}


