package example.Bean;
// Generated 2017-4-9 20:37:54 by Hibernate Tools 4.3.1



/**
 * Gimage generated by hbm2java
 */
public class Gimage  implements java.io.Serializable {


     private int gid;
     private String gplace;
     private int shopId;

    public Gimage() {
    }

	
    public Gimage(int gid, int shopId) {
        this.gid = gid;
        this.shopId = shopId;
    }
    public Gimage(int gid, String gplace, int shopId) {
       this.gid = gid;
       this.gplace = gplace;
       this.shopId = shopId;
    }
   
    public int getGid() {
        return this.gid;
    }
    
    public void setGid(int gid) {
        this.gid = gid;
    }
    public String getGplace() {
        return this.gplace;
    }
    
    public void setGplace(String gplace) {
        this.gplace = gplace;
    }
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }




}


