package example.Bean;
// Generated 2017-4-9 20:37:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Good generated by hbm2java
 */
public class Good  implements java.io.Serializable {


     private int goodId;
     private String goodname;
     private String goodimage;
     private BigDecimal inprice;
     private BigDecimal saleprice;
     private String pdate;
     private int adId;
     private int shopId;
     private Integer salenumber;

    public Good() {
    }

	
    public Good(int goodId, String goodname, BigDecimal inprice, BigDecimal saleprice, int adId, int shopId) {
        this.goodId = goodId;
        this.goodname = goodname;
        this.inprice = inprice;
        this.saleprice = saleprice;
        this.adId = adId;
        this.shopId = shopId;
    }
    public Good(int goodId, String goodname, String goodimage, BigDecimal inprice, BigDecimal saleprice, String pdate, int adId, int shopId, Integer salenumber) {
       this.goodId = goodId;
       this.goodname = goodname;
       this.goodimage = goodimage;
       this.inprice = inprice;
       this.saleprice = saleprice;
       this.pdate = pdate;
       this.adId = adId;
       this.shopId = shopId;
       this.salenumber = salenumber;
    }
   
    public int getGoodId() {
        return this.goodId;
    }
    
    public void setGoodId(int goodId) {
        this.goodId = goodId;
    }
    public String getGoodname() {
        return this.goodname;
    }
    
    public void setGoodname(String goodname) {
        this.goodname = goodname;
    }
    public String getGoodimage() {
        return this.goodimage;
    }
    
    public void setGoodimage(String goodimage) {
        this.goodimage = goodimage;
    }
    public BigDecimal getInprice() {
        return this.inprice;
    }
    
    public void setInprice(BigDecimal inprice) {
        this.inprice = inprice;
    }
    public BigDecimal getSaleprice() {
        return this.saleprice;
    }
    
    public void setSaleprice(BigDecimal saleprice) {
        this.saleprice = saleprice;
    }
    public String getPdate() {
        return this.pdate;
    }
    
    public void setPdate(String pdate) {
        this.pdate = pdate;
    }
    public int getAdId() {
        return this.adId;
    }
    
    public void setAdId(int adId) {
        this.adId = adId;
    }
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }
    public Integer getSalenumber() {
        return this.salenumber;
    }
    
    public void setSalenumber(Integer salenumber) {
        this.salenumber = salenumber;
    }




}


