package example.Bean;
// Generated 2017-4-9 20:37:54 by Hibernate Tools 4.3.1



/**
 * Orderinfo generated by hbm2java
 */
public class Orderinfo  implements java.io.Serializable {


     private int orderId;
     private String orderdate;
     private int totalmoney;
     private int userId;
     private int adId;

    public Orderinfo() {
    }

    public Orderinfo(int orderId, String orderdate, int totalmoney, int userId, int adId) {
       this.orderId = orderId;
       this.orderdate = orderdate;
       this.totalmoney = totalmoney;
       this.userId = userId;
       this.adId = adId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public String getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(String orderdate) {
        this.orderdate = orderdate;
    }
    public int getTotalmoney() {
        return this.totalmoney;
    }
    
    public void setTotalmoney(int totalmoney) {
        this.totalmoney = totalmoney;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getAdId() {
        return this.adId;
    }
    
    public void setAdId(int adId) {
        this.adId = adId;
    }




}


