package example.Bean;
// Generated 2017-4-9 20:37:54 by Hibernate Tools 4.3.1



/**
 * Shop generated by hbm2java
 */
public class Shop  implements java.io.Serializable {


     private int shopId;
     private String shopname;
     private String city;
     private String shopdescribe;
     private String shopimage;
     private int adId;

    public Shop() {
    }

	
    public Shop(int shopId, String shopname, String city, String shopdescribe, int adId) {
        this.shopId = shopId;
        this.shopname = shopname;
        this.city = city;
        this.shopdescribe = shopdescribe;
        this.adId = adId;
    }
    public Shop(int shopId, String shopname, String city, String shopdescribe, String shopimage, int adId) {
       this.shopId = shopId;
       this.shopname = shopname;
       this.city = city;
       this.shopdescribe = shopdescribe;
       this.shopimage = shopimage;
       this.adId = adId;
    }
   
    public int getShopId() {
        return this.shopId;
    }
    
    public void setShopId(int shopId) {
        this.shopId = shopId;
    }
    public String getShopname() {
        return this.shopname;
    }
    
    public void setShopname(String shopname) {
        this.shopname = shopname;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getShopdescribe() {
        return this.shopdescribe;
    }
    
    public void setShopdescribe(String shopdescribe) {
        this.shopdescribe = shopdescribe;
    }
    public String getShopimage() {
        return this.shopimage;
    }
    
    public void setShopimage(String shopimage) {
        this.shopimage = shopimage;
    }
    public int getAdId() {
        return this.adId;
    }
    
    public void setAdId(int adId) {
        this.adId = adId;
    }




}


